name: Android Build and Release

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 설정
        uses: gradle/gradle-build-action@v2

      - name: 릴리즈 빌드 실행
        run: ./gradlew assembleRelease

      - name: gradle.properties에서 버전 이름 추출
        id: get_version
        run: |
          VERSION_NAME=$(grep VERSION_NAME gradle.properties | cut -d'=' -f2 | tr -d '[:space:]')
          echo "VERSION_NAME=$VERSION_NAME"
          echo "version=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: GitHub Release에 APK 업로드
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.get_version.outputs.version }}
          tag_name: v${{ steps.get_version.outputs.version }}
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
